# Generated by Django 5.2.2 on 2025-06-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
