# Generated by Django 5.2.2 on 2025-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0003_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
